name: Fetch YouTube Serials

on:
  schedule:
    - cron: "0 2 * * *"        # every day at 02:00 UTC
  workflow_dispatch:           # allow manual run

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Fetch latest serial playlists
        env:
          YT_KEY: ${{ secrets.YT_KEY }}
        run: node playlists/serials/fetch-playlists.js

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/serials/*.json
          git commit -m "Update serial playlist videos" || echo "No changes to commit"
          git push
