
name: Update Playlist
on:
  schedule:
    - cron: "0 2 * * *"   # every day 2 AM UTC
  workflow_dispatch:

env:
  YT_KEY: ${{ secrets.YT_KEY }}    # <-- Workflow-level environment variable

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
  contents: write 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: node update.js
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update playlist.json"
