name: Update YouTube Movies

on:
  schedule:
    - cron: "0 3 * * *" # every day at 03:00 UTC
  workflow_dispatch: # manual trigger

jobs:
  update-movies:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Install dependencies reliably
      - name: Install dependencies
        run: |
          echo "📦 Installing dependencies..."
          npm install

      # 4️⃣ Run the movie playlist script
      - name: Fetch YouTube movie playlists
        env:
          YT_KEY: ${{ secrets.YT_KEY }}
        run: |
          SCRIPT="./scripts/movies-playlists.js"
          if [ -f "$SCRIPT" ]; then
            echo "🎬 Running movie playlist fetch script..."
            node "$SCRIPT" || echo "⚠️ Script failed or quota exceeded — continuing."
          else
            echo "❌ Script not found at $SCRIPT"
            exit 1
          fi

      # 5️⃣ Commit & push updated JSON if any changes
      - name: Commit and push updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/movies/*.json
          if git diff --staged --quiet; then
            echo "No updates found — skipping commit."
          else
            echo "✅ Movies JSON updated successfully — committing changes..."
            git commit -m "🔄 Update movie playlist videos (auto)"
            git push origin main
