name: Update YouTube Movies

on:
  schedule:
    - cron: "0 3 * * *" # every day at 03:00 UTC
  workflow_dispatch:  # manual trigger

jobs:
  update-movies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            npm ci || npm install
          else
            echo "No package.json found, skipping install."
          fi

      - name: Fetch YouTube movie playlists
        env:
          YT_KEY: ${{ secrets.YT_KEY }}
        run: |
          if [ -f ./scripts/movie-playlist.js ]; then
            echo "🎬 Running movie playlist fetch script..."
            node ./scripts/movie-playlist.js || echo "⚠️ Fetch failed, continuing."
          else
            echo "❌ Script not found at ./scripts/movie-playlist.js"
          fi

      - name: Commit and push updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/movies/*.json
          if git diff --staged --quiet; then
            echo "No updates found — skipping commit."
          else
            echo "✅ Movies JSON updated successfully — committing changes..."
            git commit -m "🔄 Update movie playlist videos (auto)"
            git push origin main
          fi
